### ISSUE TITLE
Glow not working again 

### ISSUE THREAD

**Issue by Vyriz** [MacHacks/CSGOGlowMac#1]
Glow has been patched again apparently. At least it's not working anymore with the same build I was using when this repo was posted and it worked then.

**Comment by mrbatblock** [comment]
Same here. Not working :I

**Comment by wo0ben** [comment]
Up same here. Doesn't work

**Comment by wo0ben** [comment]
PLEASE FIX THIS!

**Comment by ParallaxYTG** [comment]
Please fix the hack

**Comment by wo0ben** [comment]
PLS PLS PLS

I've been waiting so many days!!

**Comment by Vyriz** [comment]
Here
[Wall.zip](https://github.com/MacHacks/CSGOGlowMac/files/981563/Wall.zip)

**Comment by wo0ben** [comment]
YES FINALLY OMFG THANK YOU

**Comment by HaxGaming** [comment]
Is it working now?

**Comment by klimikus2003** [comment]
Guys, help me not working sound in csgo (music, shooting, explosives, all) I tried to check cache and reinstall game

**Comment by sonicrules11** [comment]
If you wanna use a cheat for OSX
Currently there are 2 public that are up
http://vlone.cc/
and
https://www.gosx.one/

**Comment by MacHacks** [comment]
Fixed, somewhat late...my bad. Misconfigured notifications.
